add_test([=[ShellTest.TestFork]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.TestFork]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.TestFork]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.TestForkInBackground]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.TestForkInBackground]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.TestForkInBackground]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.TestForkMixed]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.TestForkMixed]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.TestForkMixed]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.TestWait]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.TestWait]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.TestWait]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.InvalidExecCommand]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.InvalidExecCommand]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.InvalidExecCommand]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.TestInvalidCommand]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.TestInvalidCommand]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.TestInvalidCommand]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.Pwd]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.Pwd]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.Pwd]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.PwdWithArgument]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.PwdWithArgument]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.PwdWithArgument]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.PathPrompt]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.PathPrompt]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.PathPrompt]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.Exit]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.Exit]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.Exit]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.ExitWithArgument]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.ExitWithArgument]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.ExitWithArgument]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.CdForward]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.CdForward]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.CdForward]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.CdBackward]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.CdBackward]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.CdBackward]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.CDInvalidArgument]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.CDInvalidArgument]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.CDInvalidArgument]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.InternalHelpCommand]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.InternalHelpCommand]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.InternalHelpCommand]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.ExternalHelpCommand]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.ExternalHelpCommand]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.ExternalHelpCommand]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.HelpCommandNoArgument]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.HelpCommandNoArgument]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.HelpCommandNoArgument]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.DisplayLast10Commands]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.DisplayLast10Commands]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.DisplayLast10Commands]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.DisplayArguments]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.DisplayArguments]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.DisplayArguments]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.MinimumCommandNumber]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.MinimumCommandNumber]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.MinimumCommandNumber]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.CommandReverseOrder]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.CommandReverseOrder]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.CommandReverseOrder]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.CorrectCommandNumber]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.CorrectCommandNumber]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.CorrectCommandNumber]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.ReRunPreviousCommand]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.ReRunPreviousCommand]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.ReRunPreviousCommand]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.ReRunNthCommand]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.ReRunNthCommand]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.ReRunNthCommand]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.ReRunCommandInHistory]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.ReRunCommandInHistory]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.ReRunCommandInHistory]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.IllegalHistoryCommand]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.IllegalHistoryCommand]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.IllegalHistoryCommand]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.IllegalNthCommand]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.IllegalNthCommand]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.IllegalNthCommand]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.CtrlCInformation]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.CtrlCInformation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.CtrlCInformation]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.CtrlCNoCrash]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.CtrlCNoCrash]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.CtrlCNoCrash]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.CDWithoutArgument]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.CDWithoutArgument]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.CDWithoutArgument]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.CDHome]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.CDHome]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.CDHome]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.ChangeToHomeDirectory]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.ChangeToHomeDirectory]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.ChangeToHomeDirectory]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ShellTest.cdBack]=]  /Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test [==[--gtest_filter=ShellTest.cdBack]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ShellTest.cdBack]=]  PROPERTIES WORKING_DIRECTORY /Users/jenny/Desktop/Assignments/CMPT_201/A8/src SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  shell_test_TESTS ShellTest.TestFork ShellTest.TestForkInBackground ShellTest.TestForkMixed ShellTest.TestWait ShellTest.InvalidExecCommand ShellTest.TestInvalidCommand ShellTest.Pwd ShellTest.PwdWithArgument ShellTest.PathPrompt ShellTest.Exit ShellTest.ExitWithArgument ShellTest.CdForward ShellTest.CdBackward ShellTest.CDInvalidArgument ShellTest.InternalHelpCommand ShellTest.ExternalHelpCommand ShellTest.HelpCommandNoArgument ShellTest.DisplayLast10Commands ShellTest.DisplayArguments ShellTest.MinimumCommandNumber ShellTest.CommandReverseOrder ShellTest.CorrectCommandNumber ShellTest.ReRunPreviousCommand ShellTest.ReRunNthCommand ShellTest.ReRunCommandInHistory ShellTest.IllegalHistoryCommand ShellTest.IllegalNthCommand ShellTest.CtrlCInformation ShellTest.CtrlCNoCrash ShellTest.CDWithoutArgument ShellTest.CDHome ShellTest.ChangeToHomeDirectory ShellTest.cdBack)
