if(EXISTS "/Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test[1]_tests.cmake")
  include("/Users/jenny/Desktop/Assignments/CMPT_201/A8/src/shell_test[1]_tests.cmake")
else()
  add_test(shell_test_NOT_BUILT shell_test_NOT_BUILT)
endif()
